### ISSUE TITLE
"simulation time step" vs "integration time step"

### ISSUE THREAD

**Issue by jangmarker** [trieschlab/Computational-Modeling-of-Neuronal-Plasticity#21]

**Comment by tristanstoeber** [comment]
Exercise 1.3 Time Step:
Lecture notes differentiate between simulation time step and integration time step. What is the difference?

**Comment by jangmarker** [comment]
"while plotting with a fixed time step of 1ms, change the integration time step to 0.001ms, 0.01ms, 0.1ms and 1ms"

**Comment by tristanstoeber** [comment]
Agree with Jan's suggestion: "While plotting values every x ms, we vary the integration tiemstep dt ..."
