### ISSUE TITLE
Be more specific on how to implement STDP spike traces

### ISSUE THREAD

**Issue by jangmarker** [trieschlab/Computational-Modeling-of-Neuronal-Plasticity#23]

**Comment by tristanstoeber** [comment]
This question refers to "03_SpikeTimingDependentPlasticity". As of now it is stated that  

`Here you should consider the reduced symmetric interpretation (see {numref}morrison2008phenomenological_fig7). You can do this using two buffer variables that store the times of the last pre- and postsynaptic spikes.`

For those who implemented it, what other information did you miss?

**Comment by jangmarker** [comment]
I think that was it. Now that we have the figure in there, this is probably enough.
